### ISSUE TITLE
169p 부분 컴포넌트 등록

### ISSUE THREAD

**Issue by silica67sdm** [CanDoVueJS/memo-application#24]
169p code snippet 부분에서 components에 MemoForm, Memo 컴포넌트를 등록해주어야 할 거 같습니다.

**Comment by evan-moon** [comment]
제보 감사합니다 :)
말씀해주신 내용은 https://github.com/CanDoVueJS/report/blob/master/fixed/chapter5/p169.md에 추가되어있으니 참고바랍니다!
